import { defineStore } from 'pinia'
import { ref } from 'vue'

// 다국어 번역 데이터
const translations = {
  ko: {
    // 네비게이션
    "nav.home": "홈",
    "nav.services": "서비스",
    "nav.about": "소개",
    "nav.contact": "문의",
    "nav.basic": "기본 계산기",
    "nav.scientific": "공학용",
    "nav.unit": "단위 변환",
    "nav.finance": "금융",
    
    // 서브타이틀
    "subtitle": "상가 서비스 허브",
    
    // 히어로 섹션
    "hero.title": "최고의 서비스를 한 곳에서",
    "hero.subtitle": "편리하고 실용적인 도구들을 만나보세요",
    "hero.cta": "지금 시작하기",
    
    // 서비스 섹션
    "services.title": "우리의 서비스",
    "services.calculator.description": "고급 계산기 서비스로 복잡한 수학 계산을 쉽고 빠르게 해결하세요.",
    "services.calculator.features.realtime": "실시간 계산",
    "services.calculator.features.advanced": "고급 함수",
    "services.calculator.features.history": "히스토리",
    "services.calculator.use": "사용하기",
    
    // 계산기 섹션
    "calculator.basic.title": "기본 계산기",
    "calculator.basic.description": "일반적인 사칙연산을 빠르고 정확하게 계산할 수 있습니다.",
    "calculator.scientific.title": "공학용 계산기",
    "calculator.scientific.description": "삼각함수, 로그함수, 제곱근 등 고급 수학 계산을 지원합니다.",
    "calculator.unit.title": "단위 변환기",
    "calculator.unit.description": "길이, 무게, 온도, 면적, 부피 등 다양한 단위를 쉽게 변환할 수 있습니다.",
    
    // 단위 변환
    "unit.converter.type": "변환 유형:",
    "unit.types.length": "길이",
    "unit.types.weight": "무게",
    "unit.types.temperature": "온도",
    "unit.types.area": "면적",
    "unit.types.volume": "부피",
    "unit.input.placeholder": "값 입력",
    
    // 광고
    "ad.label": "Google Ads",
    "ad.banner": "Google Ads 배너",
    
    // 하단 광고
    "bottom.ad.title": "더 많은 서비스를 준비 중입니다",
    "bottom.ad.subtitle": "새로운 기능과 서비스를 기대해주세요!",
    
    // 푸터
    "footer.description": "최고의 서비스를 제공하는 상가 허브",
    "footer.services": "서비스",
    "footer.support": "고객지원",
    "footer.support.contact": "문의하기",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "이용약관",
    "footer.support.privacy": "개인정보처리방침",
    "footer.rights": "All rights reserved."
  },
  
  en: {
    "nav.home": "Home",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.basic": "Basic Calculator",
    "nav.scientific": "Scientific",
    "nav.unit": "Unit Converter",
    "nav.finance": "Finance",
    "subtitle": "Service Hub",
    "hero.title": "Best Services in One Place",
    "hero.subtitle": "Discover convenient and practical tools",
    "hero.cta": "Get Started",
    "services.title": "Our Services",
    "services.calculator.description": "Advanced calculator service to solve complex mathematical calculations easily and quickly.",
    "services.calculator.features.realtime": "Real-time Calculation",
    "services.calculator.features.advanced": "Advanced Functions",
    "services.calculator.features.history": "History",
    "services.calculator.use": "Use Now",
    "calculator.basic.title": "Basic Calculator",
    "calculator.basic.description": "Perform basic arithmetic operations quickly and accurately.",
    "calculator.scientific.title": "Scientific Calculator",
    "calculator.scientific.description": "Supports advanced mathematical calculations including trigonometric functions, logarithms, and square roots.",
    "calculator.unit.title": "Unit Converter",
    "calculator.unit.description": "Easily convert various units including length, weight, temperature, area, and volume.",
    "unit.converter.type": "Conversion Type:",
    "unit.types.length": "Length",
    "unit.types.weight": "Weight",
    "unit.types.temperature": "Temperature",
    "unit.types.area": "Area",
    "unit.types.volume": "Volume",
    "unit.input.placeholder": "Enter value",
    "ad.label": "Google Ads",
    "ad.banner": "Google Ads Banner",
    "bottom.ad.title": "More Services Coming Soon",
    "bottom.ad.subtitle": "Stay tuned for new features and services!",
    "footer.description": "Premium service hub providing the best tools",
    "footer.services": "Services",
    "footer.support": "Support",
    "footer.support.contact": "Contact Us",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Terms of Service",
    "footer.support.privacy": "Privacy Policy",
    "footer.rights": "All rights reserved."
  },
  
  ja: {
    "nav.home": "ホーム",
    "nav.services": "サービス",
    "nav.about": "会社概要",
    "nav.contact": "お問い合わせ",
    "nav.basic": "基本電卓",
    "nav.scientific": "関数電卓",
    "nav.unit": "単位変換",
    "nav.finance": "金融",
    "subtitle": "サービスハブ",
    "hero.title": "最高のサービスを一箇所で",
    "hero.subtitle": "便利で実用的なツールをお探しください",
    "hero.cta": "今すぐ始める",
    "services.title": "私たちのサービス",
    "services.calculator.description": "高度な計算機サービスで複雑な数学計算を簡単かつ迅速に解決します。",
    "services.calculator.features.realtime": "リアルタイム計算",
    "services.calculator.features.advanced": "高度な関数",
    "services.calculator.features.history": "履歴",
    "services.calculator.use": "使用する",
    "calculator.basic.title": "基本電卓",
    "calculator.basic.description": "基本的な四則演算を素早く正確に実行できます。",
    "calculator.scientific.title": "関数電卓",
    "calculator.scientific.description": "三角関数、対数関数、平方根などの高度な数学計算をサポートします。",
    "calculator.unit.title": "単位変換器",
    "calculator.unit.description": "長さ、重さ、温度、面積、体積などの様々な単位を簡単に変換できます。",
    "unit.converter.type": "変換タイプ:",
    "unit.types.length": "長さ",
    "unit.types.weight": "重さ",
    "unit.types.temperature": "温度",
    "unit.types.area": "面積",
    "unit.types.volume": "体積",
    "unit.input.placeholder": "値を入力",
    "ad.label": "Google Ads",
    "ad.banner": "Google Ads バナー",
    "bottom.ad.title": "より多くのサービスを準備中",
    "bottom.ad.subtitle": "新しい機能とサービスをお楽しみに！",
    "footer.description": "最高のサービスを提供するサービスハブ",
    "footer.services": "サービス",
    "footer.support": "サポート",
    "footer.support.contact": "お問い合わせ",
    "footer.support.faq": "よくある質問",
    "footer.support.terms": "利用規約",
    "footer.support.privacy": "プライバシーポリシー",
    "footer.rights": "All rights reserved."
  },
  
  zh: {
    "nav.home": "首页",
    "nav.services": "服务",
    "nav.about": "关于",
    "nav.contact": "联系",
    "nav.basic": "基本计算器",
    "nav.scientific": "科学计算器",
    "nav.unit": "单位转换",
    "nav.finance": "金融",
    "subtitle": "服务枢纽",
    "hero.title": "一站式最佳服务",
    "hero.subtitle": "发现便捷实用的工具",
    "hero.cta": "立即开始",
    "services.title": "我们的服务",
    "services.calculator.description": "高级计算器服务，轻松快速地解决复杂的数学计算。",
    "services.calculator.features.realtime": "实时计算",
    "services.calculator.features.advanced": "高级函数",
    "services.calculator.features.history": "历史记录",
    "services.calculator.use": "立即使用",
    "calculator.basic.title": "基本计算器",
    "calculator.basic.description": "快速准确地执行基本算术运算。",
    "calculator.scientific.title": "科学计算器",
    "calculator.scientific.description": "支持高级数学计算，包括三角函数、对数和平方根。",
    "calculator.unit.title": "单位转换器",
    "calculator.unit.description": "轻松转换各种单位，包括长度、重量、温度、面积和体积。",
    "unit.converter.type": "转换类型:",
    "unit.types.length": "长度",
    "unit.types.weight": "重量",
    "unit.types.temperature": "温度",
    "unit.types.area": "面积",
    "unit.types.volume": "体积",
    "unit.input.placeholder": "输入值",
    "ad.label": "Google Ads",
    "ad.banner": "Google Ads 横幅",
    "bottom.ad.title": "更多服务即将推出",
    "bottom.ad.subtitle": "敬请期待新功能和服务！",
    "footer.description": "提供最佳服务的服务枢纽",
    "footer.services": "服务",
    "footer.support": "支持",
    "footer.support.contact": "联系我们",
    "footer.support.faq": "常见问题",
    "footer.support.terms": "服务条款",
    "footer.support.privacy": "隐私政策",
    "footer.rights": "All rights reserved."
  },
  
  es: {
    "nav.home": "Inicio",
    "nav.services": "Servicios",
    "nav.about": "Acerca de",
    "nav.contact": "Contacto",
    "nav.basic": "Calculadora Básica",
    "nav.scientific": "Científica",
    "nav.unit": "Conversor de Unidades",
    "nav.finance": "Finanzas",
    "subtitle": "Centro de Servicios",
    "hero.title": "Los Mejores Servicios en Un Solo Lugar",
    "hero.subtitle": "Descubre herramientas convenientes y prácticas",
    "hero.cta": "Comenzar",
    "services.title": "Nuestros Servicios",
    "services.calculator.description": "Servicio de calculadora avanzada para resolver cálculos matemáticos complejos de manera fácil y rápida.",
    "services.calculator.features.realtime": "Cálculo en Tiempo Real",
    "services.calculator.features.advanced": "Funciones Avanzadas",
    "services.calculator.features.history": "Historial",
    "services.calculator.use": "Usar Ahora",
    "calculator.basic.title": "Calculadora Básica",
    "calculator.basic.description": "Realiza operaciones aritméticas básicas de manera rápida y precisa.",
    "calculator.scientific.title": "Calculadora Científica",
    "calculator.scientific.description": "Soporta cálculos matemáticos avanzados incluyendo funciones trigonométricas, logaritmos y raíces cuadradas.",
    "calculator.unit.title": "Conversor de Unidades",
    "calculator.unit.description": "Convierte fácilmente varias unidades incluyendo longitud, peso, temperatura, área y volumen.",
    "unit.converter.type": "Tipo de Conversión:",
    "unit.types.length": "Longitud",
    "unit.types.weight": "Peso",
    "unit.types.temperature": "Temperatura",
    "unit.types.area": "Área",
    "unit.types.volume": "Volumen",
    "unit.input.placeholder": "Ingresar valor",
    "ad.label": "Google Ads",
    "ad.banner": "Banner de Google Ads",
    "bottom.ad.title": "Más Servicios Próximamente",
    "bottom.ad.subtitle": "¡Mantente atento a nuevas funciones y servicios!",
    "footer.description": "Centro de servicios premium que proporciona las mejores herramientas",
    "footer.services": "Servicios",
    "footer.support": "Soporte",
    "footer.support.contact": "Contáctanos",
    "footer.support.faq": "Preguntas Frecuentes",
    "footer.support.terms": "Términos de Servicio",
    "footer.support.privacy": "Política de Privacidad",
    "footer.rights": "All rights reserved."
  },
  
  fr: {
    "nav.home": "Accueil",
    "nav.services": "Services",
    "nav.about": "À propos",
    "nav.contact": "Contact",
    "nav.basic": "Calculatrice Basique",
    "nav.scientific": "Scientifique",
    "nav.unit": "Convertisseur d'Unités",
    "nav.finance": "Finance",
    "subtitle": "Centre de Services",
    "hero.title": "Les Meilleurs Services en Un Seul Endroit",
    "hero.subtitle": "Découvrez des outils pratiques et utiles",
    "hero.cta": "Commencer",
    "services.title": "Nos Services",
    "services.calculator.description": "Service de calculatrice avancée pour résoudre facilement et rapidement les calculs mathématiques complexes.",
    "services.calculator.features.realtime": "Calcul en Temps Réel",
    "services.calculator.features.advanced": "Fonctions Avancées",
    "services.calculator.features.history": "Historique",
    "services.calculator.use": "Utiliser Maintenant",
    "calculator.basic.title": "Calculatrice Basique",
    "calculator.basic.description": "Effectuez des opérations arithmétiques de base rapidement et avec précision.",
    "calculator.scientific.title": "Calculatrice Scientifique",
    "calculator.scientific.description": "Prend en charge les calculs mathématiques avancés incluant les fonctions trigonométriques, logarithmes et racines carrées.",
    "calculator.unit.title": "Convertisseur d'Unités",
    "calculator.unit.description": "Convertissez facilement diverses unités incluant la longueur, le poids, la température, l'aire et le volume.",
    "unit.converter.type": "Type de Conversion:",
    "unit.types.length": "Longueur",
    "unit.types.weight": "Poids",
    "unit.types.temperature": "Température",
    "unit.types.area": "Aire",
    "unit.types.volume": "Volume",
    "unit.input.placeholder": "Entrer la valeur",
    "ad.label": "Google Ads",
    "ad.banner": "Bannière Google Ads",
    "bottom.ad.title": "Plus de Services à Venir",
    "bottom.ad.subtitle": "Restez à l'écoute pour de nouvelles fonctionnalités et services !",
    "footer.description": "Centre de services premium fournissant les meilleurs outils",
    "footer.services": "Services",
    "footer.support": "Support",
    "footer.support.contact": "Nous Contacter",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Conditions de Service",
    "footer.support.privacy": "Politique de Confidentialité",
    "footer.rights": "All rights reserved."
  },
  
  de: {
    "nav.home": "Startseite",
    "nav.services": "Dienste",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.basic": "Grundrechner",
    "nav.scientific": "Wissenschaftlich",
    "nav.unit": "Einheitenumrechner",
    "nav.finance": "Finanzen",
    "subtitle": "Service-Hub",
    "hero.title": "Die Besten Dienste an Einem Ort",
    "hero.subtitle": "Entdecken Sie praktische und nützliche Tools",
    "hero.cta": "Jetzt Starten",
    "services.title": "Unsere Dienste",
    "services.calculator.description": "Erweiterter Taschenrechner-Service zur einfachen und schnellen Lösung komplexer mathematischer Berechnungen.",
    "services.calculator.features.realtime": "Echtzeit-Berechnung",
    "services.calculator.features.advanced": "Erweiterte Funktionen",
    "services.calculator.features.history": "Verlauf",
    "services.calculator.use": "Jetzt Verwenden",
    "calculator.basic.title": "Grundrechner",
    "calculator.basic.description": "Führen Sie grundlegende arithmetische Operationen schnell und genau aus.",
    "calculator.scientific.title": "Wissenschaftlicher Taschenrechner",
    "calculator.scientific.description": "Unterstützt erweiterte mathematische Berechnungen einschließlich trigonometrischer Funktionen, Logarithmen und Quadratwurzeln.",
    "calculator.unit.title": "Einheitenumrechner",
    "calculator.unit.description": "Konvertieren Sie einfach verschiedene Einheiten einschließlich Länge, Gewicht, Temperatur, Fläche und Volumen.",
    "unit.converter.type": "Umrechnungstyp:",
    "unit.types.length": "Länge",
    "unit.types.weight": "Gewicht",
    "unit.types.temperature": "Temperatur",
    "unit.types.area": "Fläche",
    "unit.types.volume": "Volumen",
    "unit.input.placeholder": "Wert eingeben",
    "ad.label": "Google Ads",
    "ad.banner": "Google Ads Banner",
    "bottom.ad.title": "Weitere Dienste Kommen Bald",
    "bottom.ad.subtitle": "Bleiben Sie dran für neue Funktionen und Dienste!",
    "footer.description": "Premium-Service-Hub, der die besten Tools bereitstellt",
    "footer.services": "Dienste",
    "footer.support": "Support",
    "footer.support.contact": "Kontaktieren Sie uns",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Nutzungsbedingungen",
    "footer.support.privacy": "Datenschutzrichtlinie",
    "footer.rights": "All rights reserved."
  },
  
  ru: {
    "nav.home": "Главная",
    "nav.services": "Сервисы",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.basic": "Базовый калькулятор",
    "nav.scientific": "Научный",
    "nav.unit": "Конвертер единиц",
    "nav.finance": "Финансы",
    "subtitle": "Сервисный центр",
    "hero.title": "Лучшие сервисы в одном месте",
    "hero.subtitle": "Откройте для себя удобные и практичные инструменты",
    "hero.cta": "Начать",
    "services.title": "Наши сервисы",
    "services.calculator.description": "Продвинутый калькулятор для быстрого и легкого решения сложных математических вычислений.",
    "services.calculator.features.realtime": "Вычисления в реальном времени",
    "services.calculator.features.advanced": "Продвинутые функции",
    "services.calculator.features.history": "История",
    "services.calculator.use": "Использовать сейчас",
    "calculator.basic.title": "Базовый калькулятор",
    "calculator.basic.description": "Выполняйте основные арифметические операции быстро и точно.",
    "calculator.scientific.title": "Научный калькулятор",
    "calculator.scientific.description": "Поддерживает продвинутые математические вычисления, включая тригонометрические функции, логарифмы и квадратные корни.",
    "calculator.unit.title": "Конвертер единиц",
    "calculator.unit.description": "Легко конвертируйте различные единицы, включая длину, вес, температуру, площадь и объем.",
    "unit.converter.type": "Тип конвертации:",
    "unit.types.length": "Длина",
    "unit.types.weight": "Вес",
    "unit.types.temperature": "Температура",
    "unit.types.area": "Площадь",
    "unit.types.volume": "Объем",
    "unit.input.placeholder": "Введите значение",
    "ad.label": "Google Ads",
    "ad.banner": "Баннер Google Ads",
    "bottom.ad.title": "Больше сервисов скоро",
    "bottom.ad.subtitle": "Следите за новыми функциями и сервисами!",
    "footer.description": "Премиум сервисный центр, предоставляющий лучшие инструменты",
    "footer.services": "Сервисы",
    "footer.support": "Поддержка",
    "footer.support.contact": "Связаться с нами",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Условия использования",
    "footer.support.privacy": "Политика конфиденциальности",
    "footer.rights": "All rights reserved."
  },
  
  pt: {
    "nav.home": "Início",
    "nav.services": "Serviços",
    "nav.about": "Sobre",
    "nav.contact": "Contato",
    "nav.basic": "Calculadora Básica",
    "nav.scientific": "Científica",
    "nav.unit": "Conversor de Unidades",
    "nav.finance": "Finanças",
    "subtitle": "Hub de Serviços",
    "hero.title": "Os Melhores Serviços em Um Só Lugar",
    "hero.subtitle": "Descubra ferramentas convenientes e práticas",
    "hero.cta": "Começar",
    "services.title": "Nossos Serviços",
    "services.calculator.description": "Serviço de calculadora avançada para resolver cálculos matemáticos complexos de forma fácil e rápida.",
    "services.calculator.features.realtime": "Cálculo em Tempo Real",
    "services.calculator.features.advanced": "Funções Avanzadas",
    "services.calculator.features.history": "Histórico",
    "services.calculator.use": "Usar Agora",
    "calculator.basic.title": "Calculadora Básica",
    "calculator.basic.description": "Execute operações aritméticas básicas de forma rápida e precisa.",
    "calculator.scientific.title": "Calculadora Científica",
    "calculator.scientific.description": "Suporta cálculos matemáticos avançados incluindo funções trigonométricas, logaritmos e raízes quadradas.",
    "calculator.unit.title": "Conversor de Unidades",
    "calculator.unit.description": "Converta facilmente várias unidades incluindo comprimento, peso, temperatura, área e volume.",
    "unit.converter.type": "Tipo de Conversão:",
    "unit.types.length": "Comprimento",
    "unit.types.weight": "Peso",
    "unit.types.temperature": "Temperatura",
    "unit.types.area": "Área",
    "unit.types.volume": "Volume",
    "unit.input.placeholder": "Inserir valor",
    "ad.label": "Google Ads",
    "ad.banner": "Banner do Google Ads",
    "bottom.ad.title": "Mais Serviços em Breve",
    "bottom.ad.subtitle": "Fique atento a novos recursos e serviços!",
    "footer.description": "Hub de serviços premium fornecendo as melhores ferramentas",
    "footer.services": "Serviços",
    "footer.support": "Suporte",
    "footer.support.contact": "Entre em Contato",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Termos de Serviço",
    "footer.support.privacy": "Política de Privacidade",
    "footer.rights": "All rights reserved."
  },
  
  it: {
    "nav.home": "Home",
    "nav.services": "Servizi",
    "nav.about": "Chi Siamo",
    "nav.contact": "Contatti",
    "nav.basic": "Calcolatrice Base",
    "nav.scientific": "Scientifica",
    "nav.unit": "Convertitore di Unità",
    "nav.finance": "Finanza",
    "subtitle": "Hub di Servizi",
    "hero.title": "I Migliori Servizi in Un Solo Posto",
    "hero.subtitle": "Scopri strumenti convenienti e pratici",
    "hero.cta": "Inizia Ora",
    "services.title": "I Nostri Servizi",
    "services.calculator.description": "Servizio di calcolatrice avanzata per risolvere calcoli matematici complessi in modo facile e veloce.",
    "services.calculator.features.realtime": "Calcolo in Tempo Reale",
    "services.calculator.features.advanced": "Funzioni Avanzate",
    "services.calculator.features.history": "Cronologia",
    "services.calculator.use": "Usa Ora",
    "calculator.basic.title": "Calcolatrice Base",
    "calculator.basic.description": "Esegui operazioni aritmetiche di base in modo rapido e preciso.",
    "calculator.scientific.title": "Calcolatrice Scientifica",
    "calculator.scientific.description": "Supporta calcoli matematici avanzati inclusi funzioni trigonometriche, logaritmi e radici quadrate.",
    "calculator.unit.title": "Convertitore di Unità",
    "calculator.unit.description": "Converti facilmente varie unità inclusi lunghezza, peso, temperatura, area e volume.",
    "unit.converter.type": "Tipo di Conversione:",
    "unit.types.length": "Lunghezza",
    "unit.types.weight": "Peso",
    "unit.types.temperature": "Temperatura",
    "unit.types.area": "Area",
    "unit.types.volume": "Volume",
    "unit.input.placeholder": "Inserisci valore",
    "ad.label": "Google Ads",
    "ad.banner": "Banner Google Ads",
    "bottom.ad.title": "Altri Servizi in Arrivo",
    "bottom.ad.subtitle": "Rimani sintonizzato per nuove funzionalità e servizi!",
    "footer.description": "Hub di servizi premium che fornisce i migliori strumenti",
    "footer.services": "Servizi",
    "footer.support": "Supporto",
    "footer.support.contact": "Contattaci",
    "footer.support.faq": "FAQ",
    "footer.support.terms": "Termini di Servizio",
    "footer.support.privacy": "Informativa sulla Privacy",
    "footer.rights": "All rights reserved."
  }
}

export const useLanguageStore = defineStore('language', () => {
  const currentLanguage = ref('ko')
  
  // 저장된 언어 설정 불러오기
  const savedLanguage = localStorage.getItem('preferred-language')
  if (savedLanguage && translations[savedLanguage as keyof typeof translations]) {
    currentLanguage.value = savedLanguage
  } else {
    // 브라우저 언어 감지
    const browserLang = navigator.language.split('-')[0]
    if (translations[browserLang as keyof typeof translations]) {
      currentLanguage.value = browserLang
    }
  }
  
  // 언어 변경 함수
  function changeLanguage(lang: string) {
    if (translations[lang as keyof typeof translations]) {
      currentLanguage.value = lang
      localStorage.setItem('preferred-language', lang)
    }
  }
  
  // 번역 함수
  function t(key: string): string {
    const lang = currentLanguage.value
    const langTranslations = translations[lang as keyof typeof translations]
    return langTranslations?.[key as keyof typeof langTranslations] || key
  }
  
  return {
    currentLanguage,
    changeLanguage,
    t,
    translations
  }
}) 